//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News.App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewsID { get; set; }
        public int NewsTypeID { get; set; }
        public string NewsTitle { get; set; }
        public string NewsSummary { get; set; }
    
        public virtual NewsType NewsType { get; set; }
    }
}
